FROM alpine:3.18

RUN apk add --no-cache \
    tini \
    curl \
    openssh \
    sshfs \
    docker

RUN ssh-keygen -A \
 && passwd -d root \
 && echo -e "NoHostAuthenticationForLocalhost yes\n" > /etc/ssh/ssh_config \
 && echo -e "Port 22\nAllowTcpForwarding yes\nAllowStreamLocalForwarding yes\nGatewayPorts yes\nPermitEmptyPasswords yes\nPermitRootLogin yes\nSubsystem sftp /usr/lib/ssh/sftp-server\n" > /etc/ssh/sshd_config

EXPOSE 22

ENV XDG_RUNTIME_DIR /run/user/0

RUN mkdir -p $XDG_RUNTIME_DIR \
   && chown 0:0 $XDG_RUNTIME_DIR

# Docker Buildx Plugin
ENV DOCKER_BUILDX_VERSION="v0.11.2"
RUN mkdir -p /usr/libexec/docker/cli-plugins && curl -fsSL "https://github.com/docker/buildx/releases/download/${DOCKER_BUILDX_VERSION}/buildx-${DOCKER_BUILDX_VERSION}.linux-amd64" -o /usr/libexec/docker/cli-plugins/docker-buildx && chmod +x /usr/libexec/docker/cli-plugins/docker-buildx

# Docker-in-Docker daemon socket
 RUN touch ${XDG_RUNTIME_DIR}/docker.sock && ln -s ${XDG_RUNTIME_DIR}/docker.sock /run/docker.sock

ENTRYPOINT ["tini", "--"]
CMD ["/usr/sbin/sshd", "-4", "-D"]
