{{- if .Values.runnerRegistrationToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner-docker-autoscaler.secret" . }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
  labels:
    app: {{ include "gitlab-runner-docker-autoscaler.fullname" . }}
    chart: {{ include "gitlab-runner-docker-autoscaler.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  runner-registration-token: {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
{{- end -}}
