{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $key, $value := .Values.rbac.serviceAccountAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ include "gitlab-runner-docker-autoscaler.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.namespace | quote }}
  labels:
    app: {{ include "gitlab-runner-docker-autoscaler.fullname" . }}
    chart: {{ include "gitlab-runner-docker-autoscaler.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.rbac.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.rbac.imagePullSecrets }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end -}}
